package com.viethuynh;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/AddTravel")
public class AddTravelServlet extends HttpServlet {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String name = request.getParameter("name");
        String price = request.getParameter("price");

        String startDate = request.getParameter("startDate");
        String endDate = request.getParameter("endDate");
        String address = request.getParameter("address");
        String imageDescription = request.getParameter("imageDescription");
        String detailDescription = request.getParameter("detailDescription");

        // Create a new Travel instance
        Travel newTravel = new Travel(
            0, // ID will be generated by the DAO
            name, 
            price, 
            imageDescription, 
            detailDescription, 
            startDate, 
            endDate, 
            address
        );
        TravelDAO travelDAO = new TravelDAOImpl();
        // Use the TravelDAO to add the new Travel to the persistent storage
        travelDAO.addTravel(newTravel);

        // Redirect back to the list of travels or any other desired page
        response.sendRedirect("manageTravels");
    }
}
